version: "3.8"
services:
  postgres-db:
    image: postgres:17
    container_name: prestabanco-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prestabanco
    ports:
      - 54320:5432



  backend:
    container_name: prestabanco-backend
    image: kahaozeng/prestabanco-backend
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=192.168.1.132
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure



  frontend:
    container_name: prestabanco-frontend
    image: kahaozeng/prestabanco-frontend
    ports:
      - "8070:80"
    environment:
      - VITE_API_URL=http://192.168.1.132:8090
    deploy:
      restart_policy:
        condition: on-failure







